### ISSUE TITLE
improve

### ISSUE THREAD

**Issue by xandrck** [lubo4kaTarasenko/toy_share_back#11]
https://github.com/lubo4kaTarasenko/toy_share_back/blob/52ba31eca75214d9823953644e9806e834d78afa/app/controllers/Api/users_controller.rb#L29

```
user_params = User.find_by_email(params[:email]).attributes.slice(:name, :avatar, :email)
render json: {user: user_params}
```

but user key assume that we send an object, so response should be
```
render json: {user_params: user_params}
```

**Comment by lubo4kaTarasenko** [comment]
we send here ruby object Hash 
{user: user_params}   
user_params= {
      name: user.name,
      avatar: user.avatar,
      email: user.email
    }
