### ISSUE TITLE
posible improve

### ISSUE THREAD

**Issue by xandrck** [lubo4kaTarasenko/toy_share_back#6]
Since it's API all request will be rendered as json.
You can try to use default `defaults format: :json`
https://edgeguides.rubyonrails.org/routing.html#defining-defaults

this way response like:
```
{ products: result.products, pages: result.pages_count, user: email }
```
should work as
```
render json: { products: result.products, pages: result.pages_count, user: email }
```

**Comment by lubo4kaTarasenko** [comment]
i do not use any api gems so it doesn't work for me
