### ISSUE TITLE
logical placement

### ISSUE THREAD

**Issue by xandrck** [lubo4kaTarasenko/toy_share_back#9]
https://github.com/lubo4kaTarasenko/toy_share_back/blob/52ba31eca75214d9823953644e9806e834d78afa/app/controllers/Api/profile_controller.rb#L10
This action should be in `users/products_controller`, since it's not related to profile, it's related to products of some users.
Profile assume that all actions should be related to current user.
This way we will get right url `users/4/products` #index.

**Comment by lubo4kaTarasenko** [comment]
that makes sense but it can also stay at profile controller, `cause it is a logic for profile of specific user we wanna see. index action of products controller return info for home page not profile
